# Generated by Django 3.2.12 on 2023-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img_src',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
