# Generated by Django 3.2.12 on 2023-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi_app', '0002_movie_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
