# Generated by Django 3.2.12 on 2023-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(related_name='watchlists', to='watchlist_app.Movie'),
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
