# Generated by Django 3.2.12 on 2023-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi_app', '0001_initial'),
        ('watchlist_app', '0004_alter_watchlist_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(related_name='watchlists', to='movieapi_app.Movie'),
        ),
    ]
